drop table if exists klient CASCADE ;
drop table if exists auto CASCADE ;
drop table if exists wypozyczenie CASCADE ;
drop table if exists wypozyczenie_auta CASCADE ;

create table klient (
        id_klient bigint GENERATED BY DEFAULT AS IDENTITY not null,
        imie varchar(255),
        nazwisko varchar(255),
        primary key (id_klient)
    ); 
create table auto (
       id_auto bigint  GENERATED BY DEFAULT AS IDENTITY not null,
        nr_rejestracyjny varchar(255),
        cena double not null,
        marka varchar(255),
        model varchar(255),
        typ_paliwa varchar(255),
        primary key (id_auto)
    );
create table wypozyczenie (
       id_wypozyczenie bigint not null,
        data_wypozyczenia varchar(255),
        data_zwrotu varchar(255),
        klient_id_klient bigint,
        primary key (id_wypozyczenie)
    );
create table wypozyczenie_auta (
       wypozyczenie_id_wypozyczenie bigint not null,
        auta_id_auto bigint not null
    )
alter table auto 
       add  unique (nr_rejestracyjny);
alter table wypozyczenie_auta 
       add unique (auta_id_auto);
       
alter table wypozyczenie 
       add foreign key (klient_id_klient) 
       references klient;
alter table wypozyczenie_auta 
       add foreign key (auta_id_auto) 
       references auto;
alter table wypozyczenie_auta 
       add foreign key (wypozyczenie_id_wypozyczenie) 
       references wypozyczenie;