drop table if exists klient CASCADE ;

create table klient (
        id_klient bigint GENERATED BY DEFAULT AS IDENTITY not null,
        imie varchar(255),
        nazwisko varchar(255),
        primary key (id_klient)
    );