drop table if exists klient CASCADE ;
drop table if exists auto CASCADE ;

create table klient (
        id_klient bigint GENERATED BY DEFAULT AS IDENTITY not null,
        imie varchar(255),
        nazwisko varchar(255),
        primary key (id_klient)
    );
    
    
create table auto (
       id_auto bigint  GENERATED BY DEFAULT AS IDENTITY not null,
        nr_rejestracyjny varchar(255),
        cena double not null,
        marka varchar(255),
        model varchar(255),
        typ_paliwa varchar(255),
        primary key (id_auto)
    );
alter table auto 
       add constraint UK_dmtr16tyob5gy1homb4coworx unique (nr_rejestracyjny);